version: 0.1

phases:
  build:
    commands:
      - zip -r pipelineLambda.zip lambda; aws s3 cp pipelineLambda.zip s3://social-event-pipeline-build/updater/$CODEBUILD_BUILD_ID/pipelineLambda.zip
      - sed -i -e "s|CODEBUILD_BUILD_ID|$CODEBUILD_BUILD_ID|g" template.yml
      - aws cloudformation package --template template.yml --s3-bucket social-event-pipeline-build --output-template template-export.json

artifacts:
  type: zip
  files:
    - template-export.json