AWSTemplateFormatVersion: 2010-09-09

Parameters:
  OAuthToken:
    Type: String
    Description: Token to access github
  S3BuildBucket:
      Type: String
      Description: S3 Bucket for build artifacts
Resources:
  SnSCreateDeletePipeline:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda/createDeletePipeline.handler
      Runtime: nodejs4.3
      Role: "arn:aws:iam::644500628210:role/codepipelinebuildlambda"
      Code:
        S3Bucket: !Ref 'S3BuildBucket'
        S3Key: "updater/CODEBUILD_BUILD_ID/pipelineLambda.zip"
      Environment:
        Variables:
          O_AUTH_TOKEN: !Ref "OAuthToken"
  LogPipeline:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda/logPipeline.handler
      Runtime: nodejs4.3
      Role: "arn:aws:iam::644500628210:role/codepipelinebuildlambda"
      Code:
        S3Bucket: "social-event-pipeline-build"
        S3Key: "updater/CODEBUILD_BUILD_ID/pipelineLambda.zip"
      Environment:
        Variables:
          arntest: !Join [':',['arn','aws','lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId','function' ,!Ref 'SnSCreateDeletePipeline']]
  UpdateExistingPipelines:
      Type: AWS::Lambda::Function
      Properties:
        Handler: lambda/updateExistingPipelines.handler
        Runtime: nodejs4.3
        Role: "arn:aws:iam::644500628210:role/codepipelinebuildlambda"
        Code:
          S3Bucket: "social-event-pipeline-build"
          S3Key: "updater/CODEBUILD_BUILD_ID/pipelineLambda.zip"
        Environment:
          Variables:
            O_AUTH_TOKEN: !Ref "OAuthToken"
  SNSPipelineSubscriber:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Join [':',['arn','aws','lambda', !Ref 'AWS::Region',!Ref 'AWS::AccountId','function' ,!Ref 'SnSCreateDeletePipeline']]
      Protocol: "lambda"
      TopicArn: "arn:aws:sns:eu-central-1:644500628210:social-event-github-trigger"