AWSTemplateFormatVersion: 2010-09-09

Parameters:
  OAuthToken:
    Type: String
    Description: Token to access github

Resources:
  SnSCreateDeletePipeline:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda/createDeletePipeline.handler
      Runtime: nodejs4.3
      Role: "arn:aws:iam::644500628210:role/codepipelinebuildlambda"
      Code:
        S3Bucket: "social-event-pipeline-build"
        S3Key: "updater/CODEBUILD_BUILD_ID/pipelineLambda.zip"
      Environment:
        Variables:
          TOKEN: "bla"
  LogPipeline:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda/logPipeline.handler
      Runtime: nodejs4.3
      Role: "arn:aws:iam::644500628210:role/codepipelinebuildlambda"
      Code:
        S3Bucket: "social-event-pipeline-build"
        S3Key: "updater/CODEBUILD_BUILD_ID/pipelineLambda.zip"