AWSTemplateFormatVersion: 2010-09-09

Resources:
  SnSCreateDeletePipeline:
    Type: AWS::Lambda::Function
    Properties:
      Handler: createDeletePipeline.handler
      Runtime: nodejs4.3
      Role: "codepipelinebuildlambda"
      Code:
        S3Bucket: "social-event-pipeline-build"
        S3Key: "CODEBUILD_BUILD_ID/pipelineLambda.zip"